language: r
sudo: required
cache: packages

before_install:
  - cd pkg

r_packages:
  - testthat
  - rmarkdown
  - knitr
  - party
  - randomForest
  - randomForestSRC

r_github_packages:
  - zmjones/mmpf

notifications:
  email:
    on_success: change
    on_failure: change