language: r
sudo: required
cache: packages

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "knitr", "rmarkdown")); devtools::install_deps("pkg")'
script:
  - Rscript -e 'devtools::check("pkg")'

notifications:
  email:
    on_success: change
    on_failure: change